version: '2'

services:
  database:
       image: mongo
       restart: always
       ports:
         - "27017:27017"
       networks:
         rlcnet:
           ipv4_address: 172.10.1.12
       command: "--smallfiles --logpath=/dev/null"

  nodeapp:
       image: .
       restart: always
       ports:
          - "3001:3001"
       networks:
         rlcnet:
           ipv4_address: 172.10.1.11
       environment:
         PORT: 3001
         DB_HOST: 172.10.1.12

  webfront:
       image: nginx
       ports:
          - "80:80"
       volumes:
          - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
       restart: always
       networks:
         rlcnet:
           ipv4_address: 172.10.1.10

networks:
  rlcnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.5.254